[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino

; Cài đặt tốc độ Baud cho Serial Monitor khớp với code (115200)
monitor_speed = 115200

; Khai báo các thư viện cần tải thêm
lib_deps =
    blynkkk/Blynk @ ^1.3.2