; PlatformIO Project Configuration File
; ESP32 DevKit V1
; Tác giả: Nguyễn Duy Phong

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Thư viện cần thiết
lib_deps = 
    adafruit/DHT sensor library@^1.4.4
    adafruit/Adafruit Unified Sensor@^1.1.6
    olikraus/U8g2@^2.35.9