; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_deps = 
    blynkkk/Blynk                      ; Thư viện kết nối Blynk
    witnessmenow/UniversalTelegramBot  ; Thư viện điều khiển Telegram Bot
    bblanchon/ArduinoJson              ; Thư viện lõi để giải mã tin nhắn Telegram
    olikraus/U8g2                      ; Thư viện vẽ màn hình OLED
    adafruit/DHT sensor library        ; Thư viện đọc cảm biến DHT
    adafruit/Adafruit Unified Sensor   ; Thư viện lõi đi kèm bắt buộc của cảm biến DHT