[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
lib_ldf_mode = deep+

lib_deps =
  witnessmenow/UniversalTelegramBot
  bblanchon/ArduinoJson
  marcoschwartz/LiquidCrystal_I2C
  blynkkk/Blynk